### ISSUE TITLE
Also add to Array?

### ISSUE THREAD

**Issue by Jack-Works** [michaelficarra/proposal-iterator-chunking#2]
this should also useful for Arrays

**Comment by bakkot** [comment]
Given the experience with `groupBy` we are unlikely to be able to add new prototype methods to Array, at least not with remotely reasonable names.

**Comment by Jack-Works** [comment]
> Given the experience with `groupBy` we are unlikely to be able to add new prototype methods to Array, at least not with remotely reasonable names.

Can we try it, or have browsers given up any attempt to improve Array? (OT: we should have Array2 now)

**Comment by michaelficarra** [comment]
Browsers have pretty much given up on adding new Array prototype methods. Same opinion as https://github.com/michaelficarra/proposal-iterator-unique/issues/1 here: I'm not interested in championing new Array methods myself.

**Comment by oleedd** [comment]
>Browsers have pretty much given up on adding new Array prototype methods.

Why? Because too many methods already?

**Comment by bakkot** [comment]
Because it ends up [breaking websites](https://developer.chrome.com/blog/smooshgate) and they have to unship, which is bad for everyone.

**Comment by oleedd** [comment]
But sites are live and they will fix quickly (for example, with renaming). The same for libraries. Libraries should adjust because it's easier for them since it is not possible to know about all libraries.
Later it will be with iterators. And what, to stop adding at all?

**Comment by ljharb** [comment]
@oleedd many sites aren't and don't/won't.

**Comment by michaelficarra** [comment]
@oleedd No, websites are not live. Websites continue to exist in their current state after their maintainers have moved on or died. They don't just update themselves. See https://github.com/tc39/faq#why-dont-we-just-break-the-web.

**Comment by oleedd** [comment]
But who pays for the domain and server then?
Tried "flatten" => found a problem => changed the name. What is bad? It is better then stop adding at all.
chunk and zip are basic features. It will be required to add them for arrays anyway to not look ridiculous compared to other languages. And the names should be the same.

**Comment by oleedd** [comment]
But who pays for the domain and server then?
Tried "flatten" => found a problem => changed the name. What is bad? It is better than to stop adding at all.
chunk and zip are basic features. It will be required to add them for arrays anyway to not look ridiculous compared to other languages. And the names should be the same.

**Comment by towerofnix** [comment]
Not to revive this discussion (JavaScript is ahead of it and the place to discuss is definitely not in the issues of a proposal where the relevant person [is not interested](https://github.com/tc39/proposal-iterator-chunking/issues/2#issuecomment-1915785998) in championing something in an attempt to force the issue)...

But, just in case anyone reads back and is wondering: Because `Array.prototype.values` exists, chunking an array is as simple as doing `theArray.values().chunks()`.

**Comment by ljharb** [comment]
@towerofnix you'd need to add `.toArray()` as well to end up with an array, which isn't very performant.

**Comment by towerofnix** [comment]
In the case of wanting to consume the value as an array and not an iterable (i.e. for storage or passing into other array ops, rather than an immediate `for..of`), but right, I did forget that. Adapting or forking a polyfill (to operate directly on an array, and output an array) is probably the way to go then - where performance is at all a concern.
